### ISSUE TITLE
Acrescentar o enum CTeTipoEvento

### ISSUE THREAD

**Issue by vinicius-88** [Hercules-NET/ZeusFiscal#11]
Adicionar o enum "510630" - Registro de Passagem na Classe CTeTipoEvento

![Capturar](https://github.com/Hercules-NET/ZeusFiscal/assets/64202187/c31e5443-fd08-4223-a807-699ca5fc25a2)

**Comment by danilobreda** [comment]
Implementado pelo @marcosgerene já está no nuget!
