### ISSUE TITLE
Evento CTe 110190

### ISSUE THREAD

**Issue by vinicius-88** [Hercules-NET/ZeusFiscal#13]
Bom dia, temos o seguinte evento de CTe não implementado: "110190 - Insucesso na Entrega do CT-e”.
CTe_Nota_Tecnica_2023_002

**Comment by marcosgerene** [comment]
Implementei em #15

fiz pelo github direto do celular, alguem valida por mim, por favor.

@robertorp @danilobreda @adrbarros

**Comment by adrbarros** [comment]
Foi Adicionado também o Evento de Cancelamento de Insucesso na Entrega do CT-e - 110191
