### ISSUE TITLE
ICMSSN400

### ISSUE THREAD

**Issue by zeusvb** [Hercules-NET/ZeusFiscal#14]
Pessoal não sei se passou batido ou foi proposital mas a classe  ICMSSN400 não existe no projeto.

**Comment by marcosgerene** [comment]
CSOSN 400 entra no 102, mesma estrutura (origem + csosn)

![image](https://github.com/Hercules-NET/ZeusFiscal/assets/15945003/75034f6b-a16c-4826-8435-8eee8267b1a2)

**Comment by zeusvb** [comment]
Valeu irmão...
