### ISSUE TITLE
Retorno cancelamento e carta correcao

### ISSUE THREAD

**Issue by PedroCanizela** [Hercules-NET/ZeusFiscal#19]
Oi boa noite. Alguem sabe como tratar o retorno do evendo de cancelamento, carta de correcao

Pra retornar o  xml, chave e protocolo do evento

**Comment by adrbarros** [comment]
Bom vamos ver se consigo Explicar:
Carta de Correção
- ao fazer a chamada do método RecepcaoEventoCartaCorrecao, o mesmo retornará o Objeto RetornoRecepcaoEvento
- você deve verificar o retorno se não me engano o CStat pode ser 135 ou 136 (retornoRecepcaoEvento.Retorno.retEvento[0].infEvento.cStat)
- se estiver tudo OK, serializar guardar o XML que estará em: retornoRecepcaoEvento.ProcEventosNFe[0]
Ex: FuncoesXml.ClasseParaArquivoXml(retornoRecepcaoEvento.ProcEventosNFe[0], novoArquivo);

Cancelamento
- praticamente o mesmo conceito da carta de correção, fazer a chamada do método RecepcaoEventoCancelamento
- verificar o Cstat 135, 136, 155 se não me engano. (Olhar a tabela de Códigos dos Resultados de Processamento NFe)
- se estiver tudo OK, serializar guardar o XML que estará em: retornoRecepcaoEvento.ProcEventosNFe[0]

**Comment by PedroCanizela** [comment]
Muito obrigado, deu certo aqui
