### ISSUE TITLE
GetTotal nfe

### ISSUE THREAD

**Issue by PedroCanizela** [Hercules-NET/ZeusFiscal#20]
Ola uma duvida para todos os tipos cst ou csosn eu preciso declarar no metodo ou posso totalizar de uma maneira geral

foreach (var produto in produtos)
        {
            if (produto.imposto.IPI != null && produto.imposto.IPI.TipoIPI.GetType() == typeof(IPITrib))
                icmsTot.vIPI = icmsTot.vIPI + ((IPITrib)produto.imposto.IPI.TipoIPI).vIPI ?? 0;
            if (produto.imposto.ICMS.TipoICMS.GetType() == typeof(ICMS00))
            {
                icmsTot.vBC = icmsTot.vBC + ((ICMS00)produto.imposto.ICMS.TipoICMS).vBC;
                icmsTot.vICMS = icmsTot.vICMS + ((ICMS00)produto.imposto.ICMS.TipoICMS).vICMS;
            }
            if (produto.imposto.ICMS.TipoICMS.GetType() == typeof(ICMS20))
            {
                icmsTot.vBC = icmsTot.vBC + ((ICMS20)produto.imposto.ICMS.TipoICMS).vBC;
                icmsTot.vICMS = icmsTot.vICMS + ((ICMS20)produto.imposto.ICMS.TipoICMS).vICMS;
            }
            //Outros Ifs aqui, caso vá usar as classes ICMS00, ICMS10 para totalizar
        }

**Comment by adrbarros** [comment]
Bom eu já vou totalizando ao preencher os Objetos referente ao impostos e guardando em Variáveis definida para os Totais, ai depois só vou setando nas devidar properties da Classe icmsTot

**Comment by PedroCanizela** [comment]
Muito obrigado, fiz da mesma maneira que você comentou
