### ISSUE TITLE
Novo Evento CTe - 610111 - Cancelamento Prestacao do Servico em Desacordo

### ISSUE THREAD

**Issue by rstreit** [Hercules-NET/ZeusFiscal#24]
Olá comunidade!

Existe um evento CTe que não está implementado no aquivo CTeTipoEvento.cs:
610111 - Cancelamento Prestacao do Servico em Desacordo.

Este evento está previsto no schema evCancPrestDesacordo.xsd.

Qual é o procedimento para incluir este evento?
Desde já agradeço.

**Comment by marcosgerene** [comment]
@rstreit 

Você mesmo já disse o evento e o arquivo, só colocar lá e abrir o PR nestes casos.

Obrigado pela contribuição!
