### ISSUE TITLE
Cte Danfe impressão de xml com Colchetes [ ]  

### ISSUE THREAD

**Issue by AcesseConsult** [Hercules-NET/ZeusFiscal#29]
Peguei um xml que tem na observação dois colchetes:

` <xObs> [  NUMERO OPERACIONAL: 181100309542 / 001100004323  ]</xObs>`

Como no fast report colchetes é interpretado como expressão, ele gera um erro ao carregar o relatório:

> Erro ao gerar Danfe: Text168: Error in expression: NUMERO
> OPERACIONAL. 181100309542  / 001100004323  

![image](https://github.com/user-attachments/assets/2c87b9aa-954f-4dfe-af43-807d5e9f0723)

isso poderia ser resolvido mudando o [Allow Expression] do Text168 para False.

Como vocês tratam isso?

**Comment by danilobreda** [comment]
Acho que com allow expression funciona bem, caso consiga fazer um pull request seria legal.

**Comment by danilobreda** [comment]
@AcesseConsult resolvido com o pull #33 
Qualquer coisa estamos a disposição!
