### ISSUE TITLE
Gerar DANFE e DACTE de maneira gratuita e dentro do MacOS ou Linux

### ISSUE THREAD

**Issue by gabrielcardoso30** [Hercules-NET/ZeusFiscal#3]
Ótima noite a todos!
Gostaria de um exemplo para gerar DANFE e DACTE a partir do XML de uma nota fiscal. Não consegui encontrar nos exemplos fornecidos inicialmente.
**OBS: preciso que seja possível gerar de qualquer sistema, especialmente no MacOS e no Linux.**
Desde já, grato :D

**Comment by danilobreda** [comment]
Todos os projetos são em .net standard ou seja, cross platform, aceitando LINUX e MACOS, porem não foram testadas em MAC até hoje.

Segue projetos DEMOS:
DANFE: 
https://github.com/Hercules-NET/ZeusFiscal/tree/master/NFe.Danfe.AppTeste.OpenFast
https://github.com/Hercules-NET/ZeusFiscal/tree/master/NFe.Danfe.App.Teste.Html
DACTE:
https://github.com/Hercules-NET/ZeusFiscal/tree/master/CTe.Dacte.AppTeste

Qualquer dúvida estamos a disposição
