### ISSUE TITLE
Erro ao envia nfce feita em contingencia estado SP Portaria SRE-40/2024​​.

### ISSUE THREAD

**Issue by LosDeveloper** [Hercules-NET/ZeusFiscal#34]
**Rejeição: Parâmetro do QR-Code divergente da Nota Fiscal (digVal)**
O estado de SP tb aceita contingencia ofline desde o mes passado, mas tenho essa rejeição acima qdo tento autorizar a nfce q foi feita em contingencia. Alguem pode me ajudar

ATENÇÃO - UTILIZAÇÃO DO SAT E NFC-e
O Artigo 25 da  [Portaria CAT-147/2012](https://legislacao.fazenda.sp.gov.br/Paginas/pcat1472012.aspx) foi revogado e, portanto, não se torna mais obrigatório ao contribuinte possuir um SAT reserva Ativo. O contribuinte, nesses casos, poderá optar em ter um SAT reserva Ativo ou utilizar a NFC-e ou a ​NF-e.

Com a revogação da [Portaria CAT-12/2015](https://legislacao.fazenda.sp.gov.br/Paginas/pcat122015.aspx) pela [Portaria SRE-40/2024](https://legislacao.fazenda.sp.gov.br/Paginas/Portaria-SRE-40-de-2024.aspx) não se faz mais necessário ter um SAT Ativo para credenciamento na NFC-e. 

Em caso de falha na internet, que inviabilize a autorização da NFC-e,  o contribuinte poderá:

a. utilizar uma segunda internet cabeada;

b. utilizar uma rede móvel (ancoragem com smartphone);

c. gerar um CF-e-SAT por meio de equipamento SAT;

d. gerar uma NFC-e offline nos termos da [Portaria SRE-40/2024](https://legislacao.fazenda.sp.gov.br/Paginas/Portaria-SRE-40-de-2024.aspx)​​.

**Comment by LosDeveloper** [comment]
@danilobreda consegue me dar um help nessa questao?

**Comment by danilobreda** [comment]
@LosDeveloper não estou sabendo sobre essa questão :/

**Comment by danilobreda** [comment]
Atenção aos parametros do metodo que gera o QR CODE, em contingencia é diferente:
![image](https://github.com/user-attachments/assets/fe6feff4-9a6a-455d-b8d2-4421c3c2ced6)

**Comment by LosDeveloper** [comment]
Isso ocore para o Estado de São Paulo
@danilobreda pelo q percebi no habiente norma tpEmis=1 está normal. 
Mas na contingencia traz o seguinte erro:
<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>SP_NFCE_PL_009_V400</verAplic><cStat>104</cStat><xMotivo>Lote processado</xMotivo><cUF>35</cUF><dhRecbto>2024-08-15T18:24:22-03:00</dhRecbto><protNFe versao="4.00"><infProt><tpAmb>2</tpAmb><verAplic>SP_NFCE_PL_009_V400</verAplic><chNFe>35240803520702000194650010000000039000012349</chNFe><dhRecbto>2024-08-15T18:24:22-03:00</dhRecbto><cStat>397</cStat><xMotivo>Rejeição: Parâmetro do QR-Code divergente da Nota Fiscal (digVal)</xMotivo></infProt></protNFe></retEnviNFe>

E o qcode gerardo foi esse.
https://www.homologacao.nfce.fazenda.sp.gov.br/NFCeConsultaPublica/Paginas/ConsultaQRCode.aspx?p=35240803520702000194650010000000039000012349|2|2|13|0.10|6e57745175493639687358564c3358376e6b39416c4538564862593d|1|a93219ccdc8ab7c80d25e79f6dd63268a51bd3bb

**Comment by LosDeveloper** [comment]
@danilobreda apos a geracao da nfce, utilizei a função Nfce.Classes.Nfce.infNFeSupl.ObterUrlQrCode(...) e regerei o qrcode e deu certo.
obrigado por esclarecer acima.
