### ISSUE TITLE
Colaborando - PullRequest

### ISSUE THREAD

**Issue by jpscherer** [Hercules-NET/ZeusFiscal#45]
Olá pessoal! 
Desde já peço desculpas pela pergunta basica porem, seria a primeira vez que contribuiria para um projeto open source.
Pra abrir um PullRequest eu precisaria de uma branch porém, nao tenho permissao pra criar uma branch.
Como faco entao pra abrir um PullRequest?

**Comment by danilobreda** [comment]
Olá @jpscherer tudo certo?
Basta fazer um fork do repositório atual, fazer as mudanças no seu próprio fork e ai sim vc fazer um pullrequest dele para o Hercules.

**Comment by jpscherer** [comment]
Maravilha! obrigado.
