### ISSUE TITLE
MDFeConfiguracao é static e pode gerar problemas em ambientes com mais de uma empresa

### ISSUE THREAD

**Issue by haroflow** [Hercules-NET/ZeusFiscal#46]
Olá,

Comecei um projeto de MDF-e essa semana e reparei que a classe MDFeConfiguracao é static... ainda não testei mas acredito que possa gerar erros, pois usamos várias empresas/certificados no mesmo webservice.

Pesquisei no DFe.Net e existe um PR que confirma e corrige o problema mas ele renomeia um namespace, entre outras coisas: https://github.com/ZeusAutomacao/DFe.NET/pull/1519

Como acabei de começar o projeto, decidi abrir essa Issue para documentar. Mais para frente posso tentar ajustar e fazer um PR, se necessário.

**Comment by danilobreda** [comment]
Sim hoje o MDFe é static por ser uma implementação antiga, no passado todos os projetos era static.
O Projeto Zeus e o Hercules hoje são projetos separados, sem relação com fork, por isso não vamos "pegar" código de lá.
Porem aceitamos pullrequest para melhorias com toda certeza!

**Comment by haroflow** [comment]
Atualizei o pacote `Hercules.NET.MDFe` para a versão `2024.11.22.2159` e até agora está tudo certo, podemos fechar essa issue. Se houver necessidade abro outro PR. Obrigado!
